from enum import StrEnum


class AuthoringEventType(StrEnum):
    AGENT_CREATED = "AGENT_CREATED"
    AGENT_VERSION_CREATED = "AGENT_VERSION_CREATED"
    NODE_AGENT_BINDING_CREATED = "NODE_AGENT_BINDING_CREATED"
    TOOL_IMPORTED = "TOOL_IMPORTED"
    TOOL_CONFIG_CREATED = "TOOL_CONFIG_CREATED"
    AGENT_VERSION_TOOL_BINDING_CREATED = "AGENT_VERSION_TOOL_BINDING_CREATED"
    VERSION_PUBLISHED = "VERSION_PUBLISHED"
    VERSION_ACTIVATED = "VERSION_ACTIVATED"
    VERSION_ROLLED_BACK = "VERSION_ROLLED_BACK"
    RAG_CONFIG_CREATED = "RAG_CONFIG_CREATED"
    RAG_CONFIG_PUBLISHED = "RAG_CONFIG_PUBLISHED"
    RAG_CONFIG_DEPRECATED = "RAG_CONFIG_DEPRECATED"
    RAG_CONFIG_DISABLED = "RAG_CONFIG_DISABLED"
    TENANT_TOKEN_ISSUED = "TENANT_TOKEN_ISSUED"


class ChangeType(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"


class ResourceType(StrEnum):
    RAG_CONFIG = "rag_config"
    AGENT = "agent"
    FLOW = "flow"
    TOOL = "tool"
